/**
 * POST /api/admin/generate
 *
 * Calls Amazon Bedrock to generate 5 opinion question candidates
 * for a given topic. Falls back to hardcoded questions if Bedrock fails.
 */
import { NextResponse } from 'next/server';
import { query } from '@/lib/db/dsql';
import { generateQuestionCandidates } from '@/lib/bedrock';

export async function POST(request: Request) {
  try {
    const body = await request.json().catch(() => ({}));
    const topic = body.topic || 'Technology';

    // Fetch last 10 question texts to avoid duplicates
    let recentQuestions: string[] = [];
    try {
      const result = await query(
        `SELECT question_text FROM questions ORDER BY release_date DESC LIMIT 10`
      );
      recentQuestions = result.rows.map((r) => r.question_text);
    } catch (err) {
      console.error('[Admin Generate] Failed to fetch recent questions:', err);
      // Continue without recent questions — non-fatal
    }

    // Call Bedrock
    const { candidates, model, fallback } = await generateQuestionCandidates(
      topic,
      recentQuestions,
    );

    return NextResponse.json({
      success: true,
      topic,
      model,
      fallback,
      candidates,
      note: fallback
        ? 'AI generation failed. Showing fallback questions.'
        : `Generated by ${model}`,
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    console.error('[Admin Generate] Fatal error:', message);
    return NextResponse.json(
      { error: message, success: false },
      { status: 500 },
    );
  }
}
